#!/bin/bash -i

{
  . ~/.bash_profile
  _CONDA_BIN="/Users/chungheng/anaconda3/bin"
} &> /dev/null

exec $SHELL -i 3<<SCRIPT 4<&0 <&3
. ~/.bash_profile
export PATH="${_CONDA_BIN}:$PATH"
export PS1="\\033[48;5;195;38;5;201m[SUB]\\033[0m$PS1"
unset PYTHONHOME
. activate ${@}
exec  3>&- <&4
SCRIPT
